arm64: mach-rockchip: fix build error when SET_ETHADDR=n but SET_SN=y
When disabling SET_ETHADDR but SET_SN is still set as y, the build fails with
error: ‘CPUID_LEN’ undeclared (first use in this function)
and other errors

Fix it by defining macros under the right flags.

Fixes: c9a034c47f05 ("rockchip: board: add sn and ethaddr init control")
Signed-off-by: Eugen Hristev <eugen.hristev@collabora.com>