spl: spl_fit: add weak prototype for fpga_load
In case OPTIMIZE_DEBUG is set, unused code will not be optimized out, hence
the reference to fpga_load will be compiled.
if DM_FPGA and SPL_FPGA are not set, the build will fail with :

aarch64-none-linux-gnu-ld.bfd: common/spl/spl_fit.o: in function `spl_fit_upload_fpga':
u-boot/common/spl/spl_fit.c:595: undefined reference to `fpga_load'

By adding a weak prototype, build is successful.

Signed-off-by: Eugen Hristev <eugen.hristev@collabora.com>